
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001014
     time (cpu & wall) for ordering          =        0.250000        0.084854
     time (cpu & wall) for other matrix prep =        0.015625        0.009322
     time (cpu & wall) for value input       =        0.000000        0.001702
     time (cpu & wall) for matrix distrib.   =        0.000000        0.011418
     time (cpu & wall) for numeric factor    =        0.031250        0.041999
     computational rate (gflops) for factor  =       66.354384       49.372114

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001640
     time (cpu & wall) for matrix distrib.   =        0.015625        0.012481
     time (cpu & wall) for numeric factor    =        0.046875        0.056368
     computational rate (gflops) for factor  =       44.236256       36.786181

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001869
     time (cpu & wall) for matrix distrib.   =        0.015625        0.012787
     time (cpu & wall) for numeric factor    =        0.062500        0.051943
     computational rate (gflops) for factor  =       33.177192       39.920191

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001615
     time (cpu & wall) for matrix distrib.   =        0.015625        0.011388
     time (cpu & wall) for numeric factor    =        0.046875        0.040266
     computational rate (gflops) for factor  =       44.236256       51.496908

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =      5

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001661
     time (cpu & wall) for matrix distrib.   =        0.015625        0.011404
     time (cpu & wall) for numeric factor    =        0.046875        0.045072
     computational rate (gflops) for factor  =       44.236256       46.005314
     time (cpu & wall) for numeric solve     =        0.015625        0.004118
     computational rate (gflops) for solve   =        1.284115        4.872578
     effective I/O rate (GB/sec) for solve   =        4.784082       18.153207

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =      6

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002296
     time (cpu & wall) for matrix distrib.   =        0.015625        0.012220
     time (cpu & wall) for numeric factor    =        0.046875        0.048324
     computational rate (gflops) for factor  =       44.236256       42.909827

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.001731
     time (cpu & wall) for matrix distrib.   =        0.000000        0.012354
     time (cpu & wall) for numeric factor    =        0.046875        0.044178
     computational rate (gflops) for factor  =       44.236256       46.937131

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =      8

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001594
     time (cpu & wall) for matrix distrib.   =        0.015625        0.011842
     time (cpu & wall) for numeric factor    =        0.046875        0.044008
     computational rate (gflops) for factor  =       44.236256       47.118126

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =      9

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001846
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010793
     time (cpu & wall) for numeric factor    =        0.046875        0.046523
     computational rate (gflops) for factor  =       44.236256       44.571433
     time (cpu & wall) for numeric solve     =        0.015625        0.004665
     computational rate (gflops) for solve   =        1.284115        4.301121
     effective I/O rate (GB/sec) for solve   =        4.784082       16.024197

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     10

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001817
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010661
     time (cpu & wall) for numeric factor    =        0.031250        0.044084
     computational rate (gflops) for factor  =       66.354384       47.037322

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     11

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001579
     time (cpu & wall) for matrix distrib.   =        0.015625        0.011359
     time (cpu & wall) for numeric factor    =        0.046875        0.042520
     computational rate (gflops) for factor  =       44.236256       48.767498

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     12

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.001612
     time (cpu & wall) for matrix distrib.   =        0.000000        0.011580
     time (cpu & wall) for numeric factor    =        0.046875        0.044343
     computational rate (gflops) for factor  =       44.236256       46.761844

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     13

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001636
     time (cpu & wall) for matrix distrib.   =        0.015625        0.009689
     time (cpu & wall) for numeric factor    =        0.031250        0.041716
     computational rate (gflops) for factor  =       66.354384       49.706577

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     14

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001601
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010467
     time (cpu & wall) for numeric factor    =        0.031250        0.041039
     computational rate (gflops) for factor  =       66.354384       50.527172

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     15

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001735
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010737
     time (cpu & wall) for numeric factor    =        0.046875        0.047043
     computational rate (gflops) for factor  =       44.236256       44.078092
     time (cpu & wall) for numeric solve     =        0.015625        0.004836
     computational rate (gflops) for solve   =        1.284115        4.148516
     effective I/O rate (GB/sec) for solve   =        4.784082       15.455655

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     16

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001943
     time (cpu & wall) for matrix distrib.   =        0.015625        0.012413
     time (cpu & wall) for numeric factor    =        0.046875        0.050479
     computational rate (gflops) for factor  =       44.236256       41.078370

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     17

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001540
     time (cpu & wall) for matrix distrib.   =        0.015625        0.012553
     time (cpu & wall) for numeric factor    =        0.046875        0.089593
     computational rate (gflops) for factor  =       44.236256       23.144458

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     18

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001724
     time (cpu & wall) for matrix distrib.   =        0.015625        0.012762
     time (cpu & wall) for numeric factor    =        0.046875        0.048462
     computational rate (gflops) for factor  =       44.236256       42.787991
     time (cpu & wall) for numeric solve     =        0.015625        0.005221
     computational rate (gflops) for solve   =        1.284115        3.842926
     effective I/O rate (GB/sec) for solve   =        4.784082       14.317151

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     19

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001672
     time (cpu & wall) for matrix distrib.   =        0.015625        0.013958
     time (cpu & wall) for numeric factor    =        0.046875        0.050359
     computational rate (gflops) for factor  =       44.236256       41.175929

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     20

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002107
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010574
     time (cpu & wall) for numeric factor    =        0.046875        0.045260
     computational rate (gflops) for factor  =       44.236256       45.814827

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     21

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002097
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010398
     time (cpu & wall) for numeric factor    =        0.046875        0.041772
     computational rate (gflops) for factor  =       44.236256       49.640416

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     22

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001712
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010656
     time (cpu & wall) for numeric factor    =        0.046875        0.044195
     computational rate (gflops) for factor  =       44.236256       46.918333

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     23

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.001647
     time (cpu & wall) for matrix distrib.   =        0.000000        0.010453
     time (cpu & wall) for numeric factor    =        0.046875        0.040324
     computational rate (gflops) for factor  =       44.236256       51.422455

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     24

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001571
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010530
     time (cpu & wall) for numeric factor    =        0.046875        0.041992
     computational rate (gflops) for factor  =       44.236256       49.380698

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     25

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001792
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010924
     time (cpu & wall) for numeric factor    =        0.046875        0.042197
     computational rate (gflops) for factor  =       44.236256       49.139980
     time (cpu & wall) for numeric solve     =        0.015625        0.003822
     computational rate (gflops) for solve   =        1.284115        5.250373
     effective I/O rate (GB/sec) for solve   =        4.784082       19.560716

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     26

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.001797
     time (cpu & wall) for matrix distrib.   =        0.000000        0.011138
     time (cpu & wall) for numeric factor    =        0.046875        0.042943
     computational rate (gflops) for factor  =       44.236256       48.286446
     time (cpu & wall) for numeric solve     =        0.015625        0.003721
     computational rate (gflops) for solve   =        1.284115        5.392035
     effective I/O rate (GB/sec) for solve   =        4.784082       20.088489

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     27

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003007
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010243
     time (cpu & wall) for numeric factor    =        0.031250        0.042291
     computational rate (gflops) for factor  =       66.354384       49.031338

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB





  Performance statistics for DSP solver: icalls =     28

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19272
     no. of nonzeroes in lower triangle of a =          481701
     no. of nonzeroes in the factor l        =         5373039
     ratio of nonzeroes in factor (min/max)  =          0.7566
     number of super nodes                   =             625
     maximum order of a front matrix         =             920
     maximum size of a front matrix          =          423660
     maximum size of a front trapezoid       =          218540
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.0736D+09
     no. of floating point ops for solve     =      2.0064D+07
     ratio of flops for factor (min/max)     =          0.7240
     ratio of allocated memory (max/min)     =          1.3269
     number of positive pivots               =           19272
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001906
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010730
     time (cpu & wall) for numeric factor    =        0.031250        0.041811
     computational rate (gflops) for factor  =       66.354384       49.593757

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69013.        1. MB
                95-   1         98304.        1. MB         70813.        1. MB
                95-   2         98304.        1. MB         75165.        1. MB
                95-   3         98304.        1. MB         72832.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        287823.        2. MB


  Solver Memory allocated on core    0       =       21.794 MB
  Solver Memory allocated on core    1       =       19.701 MB
  Solver Memory allocated on core    2       =       22.375 MB
  Solver Memory allocated on core    3       =       16.863 MB
  Total Solver Memory allocated by all cores =       80.733 MB

