



  Performance statistics for DSP solver: icalls =    127

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            9711
     no. of nonzeroes in lower triangle of a =           60461
     no. of nonzeroes in the factor l        =          658055
     ratio of nonzeroes in factor (min/max)  =          0.4662
     number of super nodes                   =             741
     maximum order of a front matrix         =             222
     maximum size of a front matrix          =           24753
     maximum size of a front trapezoid       =           18867
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      4.5919D+07
     no. of floating point ops for solve     =      6.5012D+06
     ratio of flops for factor (min/max)     =          0.2488
     ratio of allocated memory (max/min)     =          1.4406
     number of positive pivots               =            9711
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000256
     time (cpu & wall) for matrix distrib.   =        0.000000        0.001991

     no input or output performed

  Solver Memory allocated on core    0       =        3.578 MB
  Solver Memory allocated on core    1       =        3.392 MB
  Solver Memory allocated on core    2       =        2.490 MB
  Solver Memory allocated on core    3       =        2.484 MB
  Total Solver Memory allocated by all cores =       11.943 MB

