
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001701
     time (cpu & wall) for ordering          =        0.171875        0.146176
     time (cpu & wall) for other matrix prep =        0.015625        0.016887
     time (cpu & wall) for value input       =        0.000000        0.002285
     time (cpu & wall) for matrix distrib.   =        0.031250        0.024981
     time (cpu & wall) for numeric factor    =        0.062500        0.068352
     computational rate (gflops) for factor  =       31.706090       28.991681

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002223
     time (cpu & wall) for matrix distrib.   =        0.015625        0.022396
     time (cpu & wall) for numeric factor    =        0.062500        0.054355
     computational rate (gflops) for factor  =       31.706090       36.456923
     time (cpu & wall) for numeric solve     =        0.015625        0.006626
     computational rate (gflops) for solve   =        1.475277        3.479164
     effective I/O rate (GB/sec) for solve   =        5.496272       12.961926

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002272
     time (cpu & wall) for matrix distrib.   =        0.015625        0.018938
     time (cpu & wall) for numeric factor    =        0.046875        0.050318
     computational rate (gflops) for factor  =       42.274787       39.382299

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003256
     time (cpu & wall) for matrix distrib.   =        0.015625        0.023316
     time (cpu & wall) for numeric factor    =        0.062500        0.062051
     computational rate (gflops) for factor  =       31.706090       31.935670
     time (cpu & wall) for numeric solve     =        0.015625        0.008487
     computational rate (gflops) for solve   =        1.475277        2.716220
     effective I/O rate (GB/sec) for solve   =        5.496272       10.119512

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =      5

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002711
     time (cpu & wall) for matrix distrib.   =        0.015625        0.018601
     time (cpu & wall) for numeric factor    =        0.046875        0.051664
     computational rate (gflops) for factor  =       42.274787       38.356270

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =      6

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002452
     time (cpu & wall) for matrix distrib.   =        0.015625        0.019474
     time (cpu & wall) for numeric factor    =        0.062500        0.053571
     computational rate (gflops) for factor  =       31.706090       36.990873

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002182
     time (cpu & wall) for matrix distrib.   =        0.015625        0.017833
     time (cpu & wall) for numeric factor    =        0.046875        0.048909
     computational rate (gflops) for factor  =       42.274787       40.516604

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =      8

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002286
     time (cpu & wall) for matrix distrib.   =        0.015625        0.020828
     time (cpu & wall) for numeric factor    =        0.062500        0.060478
     computational rate (gflops) for factor  =       31.706090       32.766357

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =      9

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002510
     time (cpu & wall) for matrix distrib.   =        0.031250        0.023212
     time (cpu & wall) for numeric factor    =        0.062500        0.071489
     computational rate (gflops) for factor  =       31.706090       27.719456

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     10

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.002342
     time (cpu & wall) for matrix distrib.   =        0.015625        0.018397
     time (cpu & wall) for numeric factor    =        0.046875        0.053471
     computational rate (gflops) for factor  =       42.274787       37.059567

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     11

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002811
     time (cpu & wall) for matrix distrib.   =        0.031250        0.026646
     time (cpu & wall) for numeric factor    =        0.062500        0.067757
     computational rate (gflops) for factor  =       31.706090       29.246096
     time (cpu & wall) for numeric solve     =        0.015625        0.006652
     computational rate (gflops) for solve   =        1.475277        3.465461
     effective I/O rate (GB/sec) for solve   =        5.496272       12.910871

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     12

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002511
     time (cpu & wall) for matrix distrib.   =        0.031250        0.019001
     time (cpu & wall) for numeric factor    =        0.046875        0.047238
     computational rate (gflops) for factor  =       42.274787       41.950282

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     13

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002308
     time (cpu & wall) for matrix distrib.   =        0.015625        0.018184
     time (cpu & wall) for numeric factor    =        0.046875        0.050666
     computational rate (gflops) for factor  =       42.274787       39.111723

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     14

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.002280
     time (cpu & wall) for matrix distrib.   =        0.015625        0.018426
     time (cpu & wall) for numeric factor    =        0.046875        0.048138
     computational rate (gflops) for factor  =       42.274787       41.165535
     time (cpu & wall) for numeric solve     =        0.015625        0.006053
     computational rate (gflops) for solve   =        1.475277        3.808417
     effective I/O rate (GB/sec) for solve   =        5.496272       14.188584

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     15

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002355
     time (cpu & wall) for matrix distrib.   =        0.015625        0.017662
     time (cpu & wall) for numeric factor    =        0.046875        0.052266
     computational rate (gflops) for factor  =       42.274787       37.914408
     time (cpu & wall) for numeric solve     =        0.015625        0.005448
     computational rate (gflops) for solve   =        1.475277        4.231442
     effective I/O rate (GB/sec) for solve   =        5.496272       15.764601

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     16

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.002267
     time (cpu & wall) for matrix distrib.   =        0.015625        0.019863
     time (cpu & wall) for numeric factor    =        0.062500        0.056902
     computational rate (gflops) for factor  =       31.706090       34.825325

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     17

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002284
     time (cpu & wall) for matrix distrib.   =        0.015625        0.018477
     time (cpu & wall) for numeric factor    =        0.046875        0.048270
     computational rate (gflops) for factor  =       42.274787       41.053389

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     18

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002175
     time (cpu & wall) for matrix distrib.   =        0.015625        0.019585
     time (cpu & wall) for numeric factor    =        0.046875        0.047259
     computational rate (gflops) for factor  =       42.274787       41.931552
     time (cpu & wall) for numeric solve     =        0.015625        0.005652
     computational rate (gflops) for solve   =        1.475277        4.078271
     effective I/O rate (GB/sec) for solve   =        5.496272       15.193950

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     19

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002198
     time (cpu & wall) for matrix distrib.   =        0.015625        0.018769
     time (cpu & wall) for numeric factor    =        0.046875        0.049904
     computational rate (gflops) for factor  =       42.274787       39.708934

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     20

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002216
     time (cpu & wall) for matrix distrib.   =        0.015625        0.018693
     time (cpu & wall) for numeric factor    =        0.046875        0.045759
     computational rate (gflops) for factor  =       42.274787       43.305528

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     21

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002986
     time (cpu & wall) for matrix distrib.   =        0.031250        0.019516
     time (cpu & wall) for numeric factor    =        0.046875        0.049593
     computational rate (gflops) for factor  =       42.274787       39.957951
     time (cpu & wall) for numeric solve     =        0.015625        0.006067
     computational rate (gflops) for solve   =        1.475277        3.799628
     effective I/O rate (GB/sec) for solve   =        5.496272       14.155841

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     22

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002286
     time (cpu & wall) for matrix distrib.   =        0.015625        0.018769
     time (cpu & wall) for numeric factor    =        0.046875        0.052183
     computational rate (gflops) for factor  =       42.274787       37.974495

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     23

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002303
     time (cpu & wall) for matrix distrib.   =        0.031250        0.018213
     time (cpu & wall) for numeric factor    =        0.046875        0.048371
     computational rate (gflops) for factor  =       42.274787       40.967498

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     24

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002384
     time (cpu & wall) for matrix distrib.   =        0.031250        0.019132
     time (cpu & wall) for numeric factor    =        0.046875        0.047214
     computational rate (gflops) for factor  =       42.274787       41.971251

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     25

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002877
     time (cpu & wall) for matrix distrib.   =        0.015625        0.019931
     time (cpu & wall) for numeric factor    =        0.062500        0.054767
     computational rate (gflops) for factor  =       31.706090       36.182866

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB





  Performance statistics for DSP solver: icalls =     26

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26715
     no. of nonzeroes in lower triangle of a =          640621
     no. of nonzeroes in the factor l        =         6248649
     ratio of nonzeroes in factor (min/max)  =          0.5673
     number of super nodes                   =             944
     maximum order of a front matrix         =             888
     maximum size of a front matrix          =          394716
     maximum size of a front trapezoid       =          228810
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.9816D+09
     no. of floating point ops for solve     =      2.3051D+07
     ratio of flops for factor (min/max)     =          0.8561
     ratio of allocated memory (max/min)     =          1.8349
     number of positive pivots               =           26715
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002377
     time (cpu & wall) for matrix distrib.   =        0.015625        0.021081
     time (cpu & wall) for numeric factor    =        0.046875        0.049342
     computational rate (gflops) for factor  =       42.274787       40.161378

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         84424.        1. MB
                95-   1         98304.        1. MB         80882.        1. MB
                95-   2        131072.        1. MB        103684.        1. MB
                95-   3        163840.        1. MB        157803.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        491520.        4. MB        426793.        3. MB


  Solver Memory allocated on core    0       =       19.850 MB
  Solver Memory allocated on core    1       =       18.040 MB
  Solver Memory allocated on core    2       =       24.911 MB
  Solver Memory allocated on core    3       =       33.102 MB
  Total Solver Memory allocated by all cores =       95.904 MB

