



  Performance statistics for DSP solver: icalls =     74

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            2444
     no. of nonzeroes in lower triangle of a =           17730
     no. of nonzeroes in the factor l        =           46370
     ratio of nonzeroes in factor (min/max)  =          0.8478
     number of super nodes                   =             187
     maximum order of a front matrix         =              36
     maximum size of a front matrix          =             666
     maximum size of a front trapezoid       =             666
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      6.2517D+05
     no. of floating point ops for solve     =      2.1270D+05
     ratio of flops for factor (min/max)     =          0.7667
     ratio of allocated memory (max/min)     =          1.6677
     number of positive pivots               =            2444
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000348
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000416
     time (cpu & wall) for matrix distrib.   =        0.000000        0.001492

     no input or output performed

  Solver Memory allocated on core    0       =        1.034 MB
  Solver Memory allocated on core    1       =        0.640 MB
  Solver Memory allocated on core    2       =        0.646 MB
  Solver Memory allocated on core    3       =        0.620 MB
  Total Solver Memory allocated by all cores =        2.940 MB





  Performance statistics for DSP solver: icalls =     75

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            3644
     no. of nonzeroes in lower triangle of a =           25610
     no. of nonzeroes in the factor l        =           64218
     ratio of nonzeroes in factor (min/max)  =          0.8870
     number of super nodes                   =             307
     maximum order of a front matrix         =              36
     maximum size of a front matrix          =             666
     maximum size of a front trapezoid       =             666
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      7.5388D+05
     no. of floating point ops for solve     =      3.7911D+05
     ratio of flops for factor (min/max)     =          0.8104
     ratio of allocated memory (max/min)     =          1.6925
     number of positive pivots               =            3644
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001011
     time (cpu & wall) for ordering          =        0.062500        0.005235
     time (cpu & wall) for other matrix prep =        0.000000        0.002589
     time (cpu & wall) for value input       =        0.000000        0.001162
     time (cpu & wall) for matrix distrib.   =        0.000000        0.002403

     no input or output performed

  Solver Memory allocated on core    0       =        1.369 MB
  Solver Memory allocated on core    1       =        0.826 MB
  Solver Memory allocated on core    2       =        0.809 MB
  Solver Memory allocated on core    3       =        0.811 MB
  Total Solver Memory allocated by all cores =        3.815 MB

