



  Performance statistics for DSP solver: icalls =    364

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            9044
     no. of nonzeroes in lower triangle of a =           84730
     no. of nonzeroes in the factor l        =          402780
     ratio of nonzeroes in factor (min/max)  =          0.9662
     number of super nodes                   =             459
     maximum order of a front matrix         =              92
     maximum size of a front matrix          =            4278
     maximum size of a front trapezoid       =            3978
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.4788D+07
     no. of floating point ops for solve     =      2.4796D+06
     ratio of flops for factor (min/max)     =          0.9455
     ratio of allocated memory (max/min)     =          1.3224
     number of positive pivots               =            9044
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001036
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.001231
     time (cpu & wall) for matrix distrib.   =        0.000000        0.004203

     no input or output performed

  Solver Memory allocated on core    0       =        3.202 MB
  Solver Memory allocated on core    1       =        2.627 MB
  Solver Memory allocated on core    2       =        2.497 MB
  Solver Memory allocated on core    3       =        2.421 MB
  Total Solver Memory allocated by all cores =       10.748 MB

