



  Performance statistics for DSP solver: icalls =     74

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            2444
     no. of nonzeroes in lower triangle of a =           15910
     no. of nonzeroes in the factor l        =           36258
     ratio of nonzeroes in factor (min/max)  =          0.9459
     number of super nodes                   =             247
     maximum order of a front matrix         =              18
     maximum size of a front matrix          =             171
     maximum size of a front trapezoid       =             171
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.5976D+05
     no. of floating point ops for solve     =      1.2486D+05
     ratio of flops for factor (min/max)     =          0.9284
     ratio of allocated memory (max/min)     =          1.6390
     number of positive pivots               =            2444
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000380
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000453
     time (cpu & wall) for matrix distrib.   =        0.000000        0.001046

     no input or output performed

  Solver Memory allocated on core    0       =        0.984 MB
  Solver Memory allocated on core    1       =        0.619 MB
  Solver Memory allocated on core    2       =        0.617 MB
  Solver Memory allocated on core    3       =        0.601 MB
  Total Solver Memory allocated by all cores =        2.821 MB





  Performance statistics for DSP solver: icalls =     75

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            3644
     no. of nonzeroes in lower triangle of a =           23790
     no. of nonzeroes in the factor l        =           54138
     ratio of nonzeroes in factor (min/max)  =          0.9633
     number of super nodes                   =             367
     maximum order of a front matrix         =              18
     maximum size of a front matrix          =             171
     maximum size of a front trapezoid       =             171
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      3.8884D+05
     no. of floating point ops for solve     =      2.4806D+05
     ratio of flops for factor (min/max)     =          0.9515
     ratio of allocated memory (max/min)     =          1.6656
     number of positive pivots               =            3644
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000979
     time (cpu & wall) for ordering          =        0.062500        0.004071
     time (cpu & wall) for other matrix prep =        0.000000        0.002383
     time (cpu & wall) for value input       =        0.000000        0.001138
     time (cpu & wall) for matrix distrib.   =        0.000000        0.002244

     no input or output performed

  Solver Memory allocated on core    0       =        1.319 MB
  Solver Memory allocated on core    1       =        0.793 MB
  Solver Memory allocated on core    2       =        0.792 MB
  Solver Memory allocated on core    3       =        0.792 MB
  Total Solver Memory allocated by all cores =        3.696 MB

