



  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            6443
     no. of nonzeroes in lower triangle of a =           39711
     no. of nonzeroes in the factor l        =          206289
     ratio of nonzeroes in factor (min/max)  =          0.7202
     number of super nodes                   =             605
     maximum order of a front matrix         =              80
     maximum size of a front matrix          =            3240
     maximum size of a front trapezoid       =            2805
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      6.5611D+06
     no. of floating point ops for solve     =      6.1728D+05
     ratio of flops for factor (min/max)     =          0.8374
     ratio of allocated memory (max/min)     =          1.9642
     number of positive pivots               =            6443
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000587
     time (cpu & wall) for matrix distrib.   =        0.000000        0.001479

     no input or output performed

  Solver Memory allocated on core    0       =        1.649 MB
  Solver Memory allocated on core    1       =        1.133 MB
  Solver Memory allocated on core    2       =        2.157 MB
  Solver Memory allocated on core    3       =        1.098 MB
  Total Solver Memory allocated by all cores =        6.038 MB

